In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection 
from sklearn.linear_model import LogisticRegression
from sklearn import datasets

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data=data.drop(["Name","Cabin","Ticket"], axis=1)

genders = {"male": 0, "female": 1}
data1 = [data]

for dataset in data1:
    dataset['Sex'] = dataset['Sex'].map(genders)
    
    
embarked = {"S": 0, "Q": 1, "C": 2}
data11 = [data]

for dataset in data11:
    dataset['Embarked'] = dataset['Embarked'].map(embarked)
    
mean = data["Age"].mean()
std = data["Age"].std() 
data.Age.fillna(mean,inplace=True)
data.Embarked.fillna(0,inplace=True)


d = data.isnull().sum()
print(d)

data=data.values
data.shape

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64


(668, 8)

In [4]:
x = data[:,:-1]
y = data[:,-1]
x.shape

(668, 7)

In [5]:
data1=pd.read_csv("test.csv")
data1=data1.drop(["Name","Cabin","Ticket"], axis=1)

genders = {"male": 0, "female": 1}
data2 = [data1]

for dataset in data2:
    dataset['Sex'] = dataset['Sex'].map(genders)

embarked = {"S": 0, "Q": 1, "C": 2}
data22 = [data1]

for dataset in data22:
    dataset['Embarked'] = dataset['Embarked'].map(embarked)    
  
    
mean = data1["Age"].mean()
std = data1["Age"].std() 
data1.Age.fillna(mean,inplace=True)
data1.Embarked.fillna(0,inplace=True)
    
d = data1.isnull().sum()
print(d) 

#data1.head(8)   
data1=data1.values
data1.shape

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64


(223, 7)

In [6]:
a = LogisticRegression()

In [7]:
from sklearn import preprocessing as pp
a.fit(x,y)

LogisticRegression()

In [8]:
a.predict(data1)

array([0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       0., 0.])

In [9]:
a.predict_proba(data1)[3]

array([0.25930789, 0.74069211])

In [10]:
y

array([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [11]:
x

array([[ 2.       ,  1.       , 29.       , ...,  0.       , 26.       ,
         0.       ],
       [ 3.       ,  0.       , 29.7005597, ...,  0.       ,  8.05     ,
         0.       ],
       [ 2.       ,  0.       , 39.       , ...,  0.       , 26.       ,
         0.       ],
       ...,
       [ 3.       ,  0.       , 32.       , ...,  0.       , 56.4958   ,
         0.       ],
       [ 3.       ,  1.       , 22.       , ...,  0.       ,  9.8375   ,
         0.       ],
       [ 3.       ,  1.       , 29.7005597, ...,  0.       , 15.5      ,
         1.       ]])

In [12]:
x[0]

array([ 2.,  1., 29.,  1.,  0., 26.,  0.])